//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detallesdepedido
    {
        public Nullable<int> idpedido { get; set; }
        public Nullable<int> idproducto { get; set; }
        public decimal preciounidad { get; set; }
        public int cantidad { get; set; }
        public decimal descuento { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual producto producto { get; set; }
    }
}
