//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebFramework.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public producto()
        {
            this.detallesdepedidos = new HashSet<detallesdepedido>();
        }
    
        public int idproducto { get; set; }
        public string nombreProducto { get; set; }
        public Nullable<int> idProveedor { get; set; }
        public Nullable<int> idCategoria { get; set; }
        public string cantidadPorUnidad { get; set; }
        public Nullable<decimal> precioUnidad { get; set; }
        public Nullable<short> unidadesEnExistencia { get; set; }
        public Nullable<short> unidadesEnPedido { get; set; }
        public Nullable<short> nivelNuevoPedido { get; set; }
        public Nullable<short> suspendido { get; set; }
        public string categoriaProducto { get; set; }
    
        public virtual categoria categoria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<detallesdepedido> detallesdepedidos { get; set; }
        public virtual proveedore proveedore { get; set; }
    }
}
